# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

ansible_vars = YAML.load_file('provisioning/vars.yml')

project_name = ansible_vars["project_name"]
project_directory = ansible_vars["project_directory"]

host_web_port = ansible_vars["host_web_port"] || 10080
host_db_port = ansible_vars["host_db_port"] || 13306

# By default this VM will use 1 processor core and 1GB of RAM. The 'VM_CPUS' and
# "VM_RAM" environment variables can be used to change that behaviour.
cpus = ENV["VM_CPUS"] || 1
ram = ENV["VM_RAM"] || 1048

Vagrant.configure(2) do |config|

  config.vm.box = "inclusivedesign/centos7"

  # Your working directory will be synced to /home/vagrant/sync in the VM.
  config.vm.synced_folder ".", "#{project_directory}"

  # From your host, connect to http://localhost:10080 to reach website or localhost:13306 for the MySQL server
  config.vm.network "forwarded_port", guest:   80, host: "#{host_web_port}", protocol: "tcp", auto_correct: true
  config.vm.network "forwarded_port", guest: 3306, host: "#{host_db_port}", protocol: "tcp", auto_correct: true

  # Port 19531 is needed so logs can be viewed using systemd-journal-gateway
  config.vm.network "forwarded_port", guest: 19531, host: 19531, protocol: "tcp",
    auto_correct: true

  config.vm.hostname = project_name

  config.vm.provider :virtualbox do |vm|
    vm.customize ["modifyvm", :id, "--memory", ram]
    vm.customize ["modifyvm", :id, "--cpus", cpus]
  end

  # The ansible-galaxy command assumes a git client is available in the VM, the
  # inclusivedesign/centos7 Vagrant box includes one.
  config.vm.provision "shell", inline: <<-SHELL
    sudo PYTHONUNBUFFERED=1 ansible-playbook #{project_directory}/provisioning/playbook.yml
  SHELL

  # 'Vagrantfile.local' should be excluded from version control.
  if File.exist? "Vagrantfile.local"
    instance_eval File.read("Vagrantfile.local"), "Vagrantfile.local"
  end

  config.vm.provision "shell", inline: "sudo systemctl restart systemd-journal-gatewayd.service",
    run: "always"

end
